//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventType.
const (
	Commit  EventType = "commit"
	Issue   EventType = "issue"
	Pr      EventType = "pr"
	Release EventType = "release"
	Review  EventType = "review"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case Commit:
		return true
	case Issue:
		return true
	case Pr:
		return true
	case Release:
		return true
	case Review:
		return true
	default:
		return false
	}
}

// Defines values for ExportFormat.
const (
	Csv  ExportFormat = "csv"
	Json ExportFormat = "json"
	Pdf  ExportFormat = "pdf"
)

// Valid indicates whether the value is a known member of the ExportFormat enum.
func (e ExportFormat) Valid() bool {
	switch e {
	case Csv:
		return true
	case Json:
		return true
	case Pdf:
		return true
	default:
		return false
	}
}

// Block One display building block.
type Block struct {
	// Data Block-type-specific payload.
	Data map[string]interface{} `json:"data"`

	// Type heading | text | list | table | keyvalue | metric | code | chart.
	Type string `json:"type"`
}

// Document An ordered list of display blocks.
type Document = []Block

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Machine-readable error code, UPPER_SNAKE_CASE.
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// Event A single ingested activity event.
type Event struct {
	Additions *int    `json:"additions,omitempty"`
	Branch    *string `json:"branch,omitempty"`
	Deletions *int    `json:"deletions,omitempty"`

	// Id Stable id: "{type}:{owner}/{repo}:{sha|number}".
	Id string `json:"id"`

	// Number PR/issue number.
	Number *int    `json:"number,omitempty"`
	Owner  string  `json:"owner"`
	Repo   string  `json:"repo"`
	Sha    *string `json:"sha,omitempty"`

	// Title Commit subject / PR title.
	Title *string `json:"title,omitempty"`

	// Ts Unix seconds.
	Ts   int64     `json:"ts"`
	Type EventType `json:"type"`
	Url  *string   `json:"url,omitempty"`
}

// EventType defines model for EventType.
type EventType string

// ExportFormat defines model for ExportFormat.
type ExportFormat string

// ExportRequest defines model for ExportRequest.
type ExportRequest struct {
	// Document An ordered list of display blocks.
	Document *Document `json:"document,omitempty"`

	// Filter Timeline filter selecting the range/scope to operate on.
	Filter     *Filter                 `json:"filter,omitempty"`
	FormValues *map[string]interface{} `json:"formValues,omitempty"`
	Format     ExportFormat            `json:"format"`
	TemplateId *string                 `json:"templateId,omitempty"`
}

// Filter Timeline filter selecting the range/scope to operate on.
type Filter struct {
	From  *int64     `json:"from,omitempty"`
	Owner *string    `json:"owner,omitempty"`
	Repo  *string    `json:"repo,omitempty"`
	To    *int64     `json:"to,omitempty"`
	Type  *EventType `json:"type,omitempty"`
}

// FormField One input field a template's form collects on run.
type FormField struct {
	// Default Default value, if any. Shape matches `type`.
	Default  interface{} `json:"default,omitempty"`
	Label    *string     `json:"label,omitempty"`
	Name     string      `json:"name"`
	Required *bool       `json:"required,omitempty"`

	// Type Form field kind, e.g. string, number, boolean, date, select.
	Type string `json:"type"`
}

// GenerateTemplateRequest defines model for GenerateTemplateRequest.
type GenerateTemplateRequest struct {
	Prompt string `json:"prompt"`
}

// RunRequest defines model for RunRequest.
type RunRequest struct {
	// Filter Timeline filter selecting the range/scope to operate on.
	Filter *Filter `json:"filter,omitempty"`

	// FormValues Values keyed by the template's form field names.
	FormValues *map[string]interface{} `json:"formValues,omitempty"`
	TemplateId string                  `json:"templateId"`
}

// Session A derived cluster of events (per owner) whose inter-event gaps are all under the sessionization threshold.
type Session struct {
	// Day Owner-local calendar day this session is grouped under.
	Day *openapi_types.Date `json:"day,omitempty"`

	// DurationHours (endTs - startTs) + lead-in padding, in hours.
	DurationHours float64 `json:"durationHours"`
	EndTs         int64   `json:"endTs"`
	Events        []Event `json:"events"`
	Owner         string  `json:"owner"`
	StartTs       int64   `json:"startTs"`
}

// SessionsResponse defines model for SessionsResponse.
type SessionsResponse struct {
	Sessions []Session `json:"sessions"`
}

// SyncJob defines model for SyncJob.
type SyncJob struct {
	JobId string `json:"jobId"`
}

// SyncStatus defines model for SyncStatus.
type SyncStatus struct {
	InProgress bool `json:"inProgress"`

	// LastSyncedTs Unix seconds of the most recent completed sync.
	LastSyncedTs int64 `json:"lastSyncedTs"`

	// PerOwner Per-owner sync counts/state, keyed by owner name.
	PerOwner map[string]interface{} `json:"perOwner"`
}

// Template defines model for Template.
type Template struct {
	Description *string        `json:"description,omitempty"`
	Exports     []ExportFormat `json:"exports"`
	Form        []FormField    `json:"form"`
	Id          string         `json:"id"`
	Layout      []Block        `json:"layout"`

	// Model Only meaningful when the layout has an LLM-backed block.
	Model     *string         `json:"model,omitempty"`
	Name      string          `json:"name"`
	Transform []TransformStep `json:"transform"`
}

// TemplateInput Template fields a client submits on create/edit (no id).
type TemplateInput struct {
	Description *string        `json:"description,omitempty"`
	Exports     []ExportFormat `json:"exports"`
	Form        []FormField    `json:"form"`
	Layout      []Block        `json:"layout"`

	// Model Only meaningful when the layout has an LLM-backed block.
	Model     *string         `json:"model,omitempty"`
	Name      string          `json:"name"`
	Transform []TransformStep `json:"transform"`
}

// TimelinePage defines model for TimelinePage.
type TimelinePage struct {
	HasMore bool    `json:"hasMore"`
	Items   []Event `json:"items"`
}

// TransformStep One step of a template's transform pipeline.
type TransformStep struct {
	// Params Primitive-specific parameters.
	Params *map[string]interface{} `json:"params,omitempty"`

	// Primitive sessionize | exclude-off-time | split-by-active-days | aggregate | group-by | rate | describe-work | passthrough.
	Primitive string `json:"primitive"`
}

// EventTypeQueryParam defines model for EventTypeQueryParam.
type EventTypeQueryParam = EventType

// FromQueryParam defines model for FromQueryParam.
type FromQueryParam = int64

// GapQueryParam defines model for GapQueryParam.
type GapQueryParam = int64

// OwnerQueryParam defines model for OwnerQueryParam.
type OwnerQueryParam = string

// OwnerQueryParamRequired defines model for OwnerQueryParamRequired.
type OwnerQueryParamRequired = string

// PageQueryParam defines model for PageQueryParam.
type PageQueryParam = int

// PerPageQueryParam defines model for PerPageQueryParam.
type PerPageQueryParam = int

// RepoQueryParam defines model for RepoQueryParam.
type RepoQueryParam = string

// TemplateIdPathParam defines model for TemplateIdPathParam.
type TemplateIdPathParam = string

// ToQueryParam defines model for ToQueryParam.
type ToQueryParam = int64

// Error defines model for Error.
type Error = ErrorResponse

// ListReposParams defines parameters for ListRepos.
type ListReposParams struct {
	// Owner Owner/org to list repos for.
	Owner OwnerQueryParamRequired `form:"owner" json:"owner"`
}

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	// Owner Filter by owner/org.
	Owner *OwnerQueryParam `form:"owner,omitempty" json:"owner,omitempty"`

	// From Range start, unix seconds (inclusive).
	From *FromQueryParam `form:"from,omitempty" json:"from,omitempty"`

	// To Range end, unix seconds (exclusive).
	To *ToQueryParam `form:"to,omitempty" json:"to,omitempty"`

	// Gap Inter-event gap threshold, in seconds, overriding GITRAKZ_SESSION_GAP for this request's sessionization.
	Gap *GapQueryParam `form:"gap,omitempty" json:"gap,omitempty"`
}

// ListTimelineParams defines parameters for ListTimeline.
type ListTimelineParams struct {
	// Owner Filter by owner/org.
	Owner *OwnerQueryParam `form:"owner,omitempty" json:"owner,omitempty"`

	// Repo Filter by repo.
	Repo *RepoQueryParam `form:"repo,omitempty" json:"repo,omitempty"`

	// Type Filter by event type.
	Type *EventTypeQueryParam `form:"type,omitempty" json:"type,omitempty"`

	// From Range start, unix seconds (inclusive).
	From *FromQueryParam `form:"from,omitempty" json:"from,omitempty"`

	// To Range end, unix seconds (exclusive).
	To *ToQueryParam `form:"to,omitempty" json:"to,omitempty"`

	// Page 1-indexed page number.
	Page *PageQueryParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Page size.
	PerPage *PerPageQueryParam `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// ExportDocumentJSONRequestBody defines body for ExportDocument for application/json ContentType.
type ExportDocumentJSONRequestBody = ExportRequest

// RunTemplateJSONRequestBody defines body for RunTemplate for application/json ContentType.
type RunTemplateJSONRequestBody = RunRequest

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = TemplateInput

// GenerateTemplateJSONRequestBody defines body for GenerateTemplate for application/json ContentType.
type GenerateTemplateJSONRequestBody = GenerateTemplateRequest

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody = TemplateInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ExportDocument Export a document (or a template run) to a file
	// (POST /api/export)
	ExportDocument(w http.ResponseWriter, r *http.Request)
	// ListOwners List distinct owners/orgs
	// (GET /api/owners)
	ListOwners(w http.ResponseWriter, r *http.Request)
	// ListRepos List repos under an owner
	// (GET /api/repos)
	ListRepos(w http.ResponseWriter, r *http.Request, params ListReposParams)
	// RunTemplate Run a template's transform pipeline over a filtered range
	// (POST /api/run)
	RunTemplate(w http.ResponseWriter, r *http.Request)
	// ListSessions Derived, sessionized view of the timeline
	// (GET /api/sessions)
	ListSessions(w http.ResponseWriter, r *http.Request, params ListSessionsParams)
	// TriggerSync Trigger an incremental sync of activity from `gh`
	// (POST /api/sync)
	TriggerSync(w http.ResponseWriter, r *http.Request)
	// GetSyncStatus Current sync status
	// (GET /api/sync/status)
	GetSyncStatus(w http.ResponseWriter, r *http.Request)
	// ListTemplates List templates (built-in + custom)
	// (GET /api/templates)
	ListTemplates(w http.ResponseWriter, r *http.Request)
	// CreateTemplate Create a custom template
	// (POST /api/templates)
	CreateTemplate(w http.ResponseWriter, r *http.Request)
	// GenerateTemplate LLM-compose a template draft from a description
	// (POST /api/templates/generate)
	GenerateTemplate(w http.ResponseWriter, r *http.Request)
	// DeleteTemplate Delete a custom template
	// (DELETE /api/templates/{id})
	DeleteTemplate(w http.ResponseWriter, r *http.Request, id TemplateIdPathParam)
	// UpdateTemplate Edit a template
	// (PUT /api/templates/{id})
	UpdateTemplate(w http.ResponseWriter, r *http.Request, id TemplateIdPathParam)
	// ListTimeline Paginated, filterable event timeline
	// (GET /api/timeline)
	ListTimeline(w http.ResponseWriter, r *http.Request, params ListTimelineParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ExportDocument operation middleware
func (siw *ServerInterfaceWrapper) ExportDocument(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportDocument(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOwners operation middleware
func (siw *ServerInterfaceWrapper) ListOwners(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOwners(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepos operation middleware
func (siw *ServerInterfaceWrapper) ListRepos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReposParams

	// ------------- Required query parameter "owner" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunTemplate operation middleware
func (siw *ServerInterfaceWrapper) RunTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSessionsParams

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "gap" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "gap", r.URL.Query(), &params.Gap, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "gap"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gap", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerSync(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSyncStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSyncStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSyncStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListTemplates(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTemplates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateTemplate operation middleware
func (siw *ServerInterfaceWrapper) GenerateTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTemplate operation middleware
func (siw *ServerInterfaceWrapper) DeleteTemplate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TemplateIdPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTemplate operation middleware
func (siw *ServerInterfaceWrapper) UpdateTemplate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TemplateIdPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTimeline operation middleware
func (siw *ServerInterfaceWrapper) ListTimeline(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTimelineParams

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "repo" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "repo", r.URL.Query(), &params.Repo, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "repo"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "per_page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTimeline(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/owners", wrapper.ListOwners)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/repos", wrapper.ListRepos)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/timeline", wrapper.ListTimeline)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/sessions", wrapper.ListSessions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/sync", wrapper.TriggerSync)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/sync/status", wrapper.GetSyncStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/templates", wrapper.ListTemplates)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/templates", wrapper.CreateTemplate)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/templates/{id}", wrapper.DeleteTemplate)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/templates/{id}", wrapper.UpdateTemplate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/templates/generate", wrapper.GenerateTemplate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/run", wrapper.RunTemplate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/export", wrapper.ExportDocument)

	return m
}

type ErrorJSONResponse ErrorResponse

type ExportDocumentRequestObject struct {
	Body *ExportDocumentJSONRequestBody
}

type ExportDocumentResponseObject interface {
	VisitExportDocumentResponse(w http.ResponseWriter) error
}

type ExportDocument200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ExportDocument200ApplicationoctetStreamResponse) VisitExportDocumentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExportDocumentdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ExportDocumentdefaultJSONResponse) VisitExportDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnersRequestObject struct {
}

type ListOwnersResponseObject interface {
	VisitListOwnersResponse(w http.ResponseWriter) error
}

type ListOwners200JSONResponse []string

func (response ListOwners200JSONResponse) VisitListOwnersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnersdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListOwnersdefaultJSONResponse) VisitListOwnersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListReposRequestObject struct {
	Params ListReposParams
}

type ListReposResponseObject interface {
	VisitListReposResponse(w http.ResponseWriter) error
}

type ListRepos200JSONResponse []string

func (response ListRepos200JSONResponse) VisitListReposResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListReposdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListReposdefaultJSONResponse) VisitListReposResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RunTemplateRequestObject struct {
	Body *RunTemplateJSONRequestBody
}

type RunTemplateResponseObject interface {
	VisitRunTemplateResponse(w http.ResponseWriter) error
}

type RunTemplate200JSONResponse Document

func (response RunTemplate200JSONResponse) VisitRunTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RunTemplate200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response RunTemplate200TexteventStreamResponse) VisitRunTemplateResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type RunTemplatedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response RunTemplatedefaultJSONResponse) VisitRunTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessionsRequestObject struct {
	Params ListSessionsParams
}

type ListSessionsResponseObject interface {
	VisitListSessionsResponse(w http.ResponseWriter) error
}

type ListSessions200JSONResponse SessionsResponse

func (response ListSessions200JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessionsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListSessionsdefaultJSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSyncRequestObject struct {
}

type TriggerSyncResponseObject interface {
	VisitTriggerSyncResponse(w http.ResponseWriter) error
}

type TriggerSync202JSONResponse SyncJob

func (response TriggerSync202JSONResponse) VisitTriggerSyncResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSyncdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response TriggerSyncdefaultJSONResponse) VisitTriggerSyncResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSyncStatusRequestObject struct {
}

type GetSyncStatusResponseObject interface {
	VisitGetSyncStatusResponse(w http.ResponseWriter) error
}

type GetSyncStatus200JSONResponse SyncStatus

func (response GetSyncStatus200JSONResponse) VisitGetSyncStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSyncStatusdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetSyncStatusdefaultJSONResponse) VisitGetSyncStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListTemplatesRequestObject struct {
}

type ListTemplatesResponseObject interface {
	VisitListTemplatesResponse(w http.ResponseWriter) error
}

type ListTemplates200JSONResponse []Template

func (response ListTemplates200JSONResponse) VisitListTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTemplatesdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListTemplatesdefaultJSONResponse) VisitListTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTemplateRequestObject struct {
	Body *CreateTemplateJSONRequestBody
}

type CreateTemplateResponseObject interface {
	VisitCreateTemplateResponse(w http.ResponseWriter) error
}

type CreateTemplate200JSONResponse Template

func (response CreateTemplate200JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTemplatedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CreateTemplatedefaultJSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateTemplateRequestObject struct {
	Body *GenerateTemplateJSONRequestBody
}

type GenerateTemplateResponseObject interface {
	VisitGenerateTemplateResponse(w http.ResponseWriter) error
}

type GenerateTemplate200JSONResponse Template

func (response GenerateTemplate200JSONResponse) VisitGenerateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateTemplatedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GenerateTemplatedefaultJSONResponse) VisitGenerateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTemplateRequestObject struct {
	Id TemplateIdPathParam `json:"id"`
}

type DeleteTemplateResponseObject interface {
	VisitDeleteTemplateResponse(w http.ResponseWriter) error
}

type DeleteTemplate204Response struct {
}

func (response DeleteTemplate204Response) VisitDeleteTemplateResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTemplatedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response DeleteTemplatedefaultJSONResponse) VisitDeleteTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTemplateRequestObject struct {
	Id   TemplateIdPathParam `json:"id"`
	Body *UpdateTemplateJSONRequestBody
}

type UpdateTemplateResponseObject interface {
	VisitUpdateTemplateResponse(w http.ResponseWriter) error
}

type UpdateTemplate200JSONResponse Template

func (response UpdateTemplate200JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTemplatedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response UpdateTemplatedefaultJSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListTimelineRequestObject struct {
	Params ListTimelineParams
}

type ListTimelineResponseObject interface {
	VisitListTimelineResponse(w http.ResponseWriter) error
}

type ListTimeline200JSONResponse TimelinePage

func (response ListTimeline200JSONResponse) VisitListTimelineResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTimelinedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListTimelinedefaultJSONResponse) VisitListTimelineResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ExportDocument Export a document (or a template run) to a file
	// (POST /api/export)
	ExportDocument(ctx context.Context, request ExportDocumentRequestObject) (ExportDocumentResponseObject, error)
	// ListOwners List distinct owners/orgs
	// (GET /api/owners)
	ListOwners(ctx context.Context, request ListOwnersRequestObject) (ListOwnersResponseObject, error)
	// ListRepos List repos under an owner
	// (GET /api/repos)
	ListRepos(ctx context.Context, request ListReposRequestObject) (ListReposResponseObject, error)
	// RunTemplate Run a template's transform pipeline over a filtered range
	// (POST /api/run)
	RunTemplate(ctx context.Context, request RunTemplateRequestObject) (RunTemplateResponseObject, error)
	// ListSessions Derived, sessionized view of the timeline
	// (GET /api/sessions)
	ListSessions(ctx context.Context, request ListSessionsRequestObject) (ListSessionsResponseObject, error)
	// TriggerSync Trigger an incremental sync of activity from `gh`
	// (POST /api/sync)
	TriggerSync(ctx context.Context, request TriggerSyncRequestObject) (TriggerSyncResponseObject, error)
	// GetSyncStatus Current sync status
	// (GET /api/sync/status)
	GetSyncStatus(ctx context.Context, request GetSyncStatusRequestObject) (GetSyncStatusResponseObject, error)
	// ListTemplates List templates (built-in + custom)
	// (GET /api/templates)
	ListTemplates(ctx context.Context, request ListTemplatesRequestObject) (ListTemplatesResponseObject, error)
	// CreateTemplate Create a custom template
	// (POST /api/templates)
	CreateTemplate(ctx context.Context, request CreateTemplateRequestObject) (CreateTemplateResponseObject, error)
	// GenerateTemplate LLM-compose a template draft from a description
	// (POST /api/templates/generate)
	GenerateTemplate(ctx context.Context, request GenerateTemplateRequestObject) (GenerateTemplateResponseObject, error)
	// DeleteTemplate Delete a custom template
	// (DELETE /api/templates/{id})
	DeleteTemplate(ctx context.Context, request DeleteTemplateRequestObject) (DeleteTemplateResponseObject, error)
	// UpdateTemplate Edit a template
	// (PUT /api/templates/{id})
	UpdateTemplate(ctx context.Context, request UpdateTemplateRequestObject) (UpdateTemplateResponseObject, error)
	// ListTimeline Paginated, filterable event timeline
	// (GET /api/timeline)
	ListTimeline(ctx context.Context, request ListTimelineRequestObject) (ListTimelineResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ExportDocument operation middleware
func (sh *strictHandler) ExportDocument(w http.ResponseWriter, r *http.Request) {
	var request ExportDocumentRequestObject

	var body ExportDocumentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportDocument(ctx, request.(ExportDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportDocumentResponseObject); ok {
		if err := validResponse.VisitExportDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOwners operation middleware
func (sh *strictHandler) ListOwners(w http.ResponseWriter, r *http.Request) {
	var request ListOwnersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOwners(ctx, request.(ListOwnersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOwners")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOwnersResponseObject); ok {
		if err := validResponse.VisitListOwnersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRepos operation middleware
func (sh *strictHandler) ListRepos(w http.ResponseWriter, r *http.Request, params ListReposParams) {
	var request ListReposRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRepos(ctx, request.(ListReposRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRepos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListReposResponseObject); ok {
		if err := validResponse.VisitListReposResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RunTemplate operation middleware
func (sh *strictHandler) RunTemplate(w http.ResponseWriter, r *http.Request) {
	var request RunTemplateRequestObject

	var body RunTemplateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunTemplate(ctx, request.(RunTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunTemplateResponseObject); ok {
		if err := validResponse.VisitRunTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSessions operation middleware
func (sh *strictHandler) ListSessions(w http.ResponseWriter, r *http.Request, params ListSessionsParams) {
	var request ListSessionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSessions(ctx, request.(ListSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSessionsResponseObject); ok {
		if err := validResponse.VisitListSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerSync operation middleware
func (sh *strictHandler) TriggerSync(w http.ResponseWriter, r *http.Request) {
	var request TriggerSyncRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerSync(ctx, request.(TriggerSyncRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerSync")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerSyncResponseObject); ok {
		if err := validResponse.VisitTriggerSyncResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSyncStatus operation middleware
func (sh *strictHandler) GetSyncStatus(w http.ResponseWriter, r *http.Request) {
	var request GetSyncStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSyncStatus(ctx, request.(GetSyncStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSyncStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSyncStatusResponseObject); ok {
		if err := validResponse.VisitGetSyncStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTemplates operation middleware
func (sh *strictHandler) ListTemplates(w http.ResponseWriter, r *http.Request) {
	var request ListTemplatesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTemplates(ctx, request.(ListTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTemplates")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTemplatesResponseObject); ok {
		if err := validResponse.VisitListTemplatesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTemplate operation middleware
func (sh *strictHandler) CreateTemplate(w http.ResponseWriter, r *http.Request) {
	var request CreateTemplateRequestObject

	var body CreateTemplateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTemplate(ctx, request.(CreateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTemplateResponseObject); ok {
		if err := validResponse.VisitCreateTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateTemplate operation middleware
func (sh *strictHandler) GenerateTemplate(w http.ResponseWriter, r *http.Request) {
	var request GenerateTemplateRequestObject

	var body GenerateTemplateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateTemplate(ctx, request.(GenerateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateTemplateResponseObject); ok {
		if err := validResponse.VisitGenerateTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTemplate operation middleware
func (sh *strictHandler) DeleteTemplate(w http.ResponseWriter, r *http.Request, id TemplateIdPathParam) {
	var request DeleteTemplateRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTemplate(ctx, request.(DeleteTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTemplateResponseObject); ok {
		if err := validResponse.VisitDeleteTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTemplate operation middleware
func (sh *strictHandler) UpdateTemplate(w http.ResponseWriter, r *http.Request, id TemplateIdPathParam) {
	var request UpdateTemplateRequestObject

	request.Id = id

	var body UpdateTemplateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTemplate(ctx, request.(UpdateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTemplateResponseObject); ok {
		if err := validResponse.VisitUpdateTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTimeline operation middleware
func (sh *strictHandler) ListTimeline(w http.ResponseWriter, r *http.Request, params ListTimelineParams) {
	var request ListTimelineRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTimeline(ctx, request.(ListTimelineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTimeline")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTimelineResponseObject); ok {
		if err := validResponse.VisitListTimelineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fvdc9s4kv9XunhXtXENZSVze/fgecokTja7yUQnOfdws6kYIlskJiDAAUDZGlv/+1UD/BShD6/tu626",
	"N0kEGo3+wq9/oO6iRBWlkiitiS7uopJpVqBF7b5drlHaq02J/1mh3szoGf2cokk0Ly1XMrqI3nFhUcNy",
	"A0jDwW5KPI/iiNPD32liFEeSFRhdRPQsiiOT5FgwEvWvGlfRRfQv006NqX9qpu3q0XYbR++0Kg6pMWcy",
	"QzCWaRtDJfktGEyUTA284DIRleFrPNun10qrYqDXSumC2egi4tL+x5+j2GvuvmKG2mn0npWHFPogLeqJ",
	"t0nGSrC5RpMrkcbAZaNcDGqNWvOUywzef7iav/7bf39bXC4WHz7/8u396xmslAabcwMaf6/Q2D8ZMGgM",
	"V5L/wWilfVvKWPngHX2+kahP87WioVOls33ruwEDDeoFjdVcZqH15vh7xTWm43U/N6uBVSC4saCxVIas",
	"c2x93Qq1usLD+sxYdjDUX024TPEWUyhZhiCrYol7FaAhg/2nuGKVsNHFqzgquORFVbjPAUfMUB/ThZ6D",
	"4X/szbUS9bf9Ovz7yzgq2K1X4seXL4+qNMdSnRYa5Jp9StGzI0FxhUUpmMUP6YzZvF3NSSuZzTthPH2g",
	"f6/U8QqCMt2tH3h7rH5Y9cBc25LiplTSoK+0WitNHxIlLUpLH1lZCp64JJ/+ZkjFu1MrJ0mb1/L9asOt",
	"vpaANAZUklRaY3ru7FPPJ/E/C5V8DySiREi5KQXbwLLiwtWtJY0l05Ralagt93tKmWVjCU7whAwyMSUm",
	"fMUTKNlGKJaed5ZSy98wsdG2+WFXSo7MLX0PFm8t3PuicA+WLQXCPXzHzZqJij4WaDVP4B4SldL3JGfa",
	"9pbqxUcXS782R5XbxNeAXm9VUhW1p0bGVTpFjanXSq06k9HmjYsii4U55kfvhNYIEdOabej70MF0bg8s",
	"Tzsd6/WJJTmXONHIUmcmHwI0OIYvs9nl/Nvil9d/u/z25vXiMmAgCiLLuDBdcv3aGCSOZCVE9HUbRwUa",
	"Q2UnmIF9Czstu/EhIzsIELAwGC4zgcBlhsZiCiyxfM1tjUHGscjSlNPkge5NOvaUX2omk7w/qFa+NyZF",
	"gafI4oGDbOEDlKcX8PfojiZvL+7cUbWd3lFx3F7cmZzd+6Nl+/co6Af/NHAmzKfcmKp/Mh3Qz5+QYzfF",
	"vkqHHpicHbaN5VYEQu+NKgpuwVTOszCF2Rzc0L6KAWlmLOpLrzTT7KO1tishJ4LNOKq0GJTxSvMDeu6E",
	"tTuVrGkmxD0kUqr9UX5VK4mSzmDKDjKZC2Q3d83xhuoG+df9IJCZftZ0Xrq8LZW272rteyLNmuSlqyiO",
	"3IGyf/Lco81xaUl7Ze+QPdvyuI2jlYMGx2Z4AOHGK138F1XvQeoyMetp4g/7kSlX7aYPOrtvIAqQFnIc",
	"r1r1CiE/vmv3OQzZK16g4BLBGwIMCkwsHV82R9AEO6YmUSUSuqUtMovgkf3Q+K5NOQVf/EPJbdWJsh+Y",
	"T9uQqZQu3nEUaRhicFlWFlY0ABg07vmTA/wFJEqQAQ0oCboK2KlFubuy3/oH4LBBDHwFTG7OYZGzEqFg",
	"NsnRwDVpe31Oagq2RHG44nkEGLRzv5upFVoxYbq4XSolkMn9MIfMVJvhOydgiufZOfg14rrKx1CLiSFl",
	"FuM6vI4jHKd5PSgUzu9RulBsAPnemlBqVZT2eOrU40JrzSu5V/zzlY+hsf0cgo6YUh9Dybkbet4XZDkT",
	"RqsPqCS9sSGTLHybH0I/KWq+xhSoLaGColYe9xh4UdJXyv0zuMmVoVQa0BAGmEZgQkAlU9Ruk0NCoSMq",
	"QpB+s6c5nwiVMAEJEyhTpiFlG89b1MKBG8i0qkpM/cqDs5sCNwg4K+10+ouqdAALvECZXhmYeNrnypzB",
	"DyCQpRMuoSTHU5ZwCTlNHy6oqqXoLVkjqm0cOZEnFkJvdNedngLnPZoNwPn9xbre2KkETj+8WgKmFtFs",
	"bdeq7TYOBKHZ32vU/j3dCk1cj+ywo38rOKjXRiZ/VcuxOr+p5Sm554ftk7ywzFZmLJzLmVaZRtOD/v0i",
	"LpixNB/rENqPXCllKfUK5bishLKTbCWQuhmzkcmJ2LZE/bmJntNL3Qz1xMWHWwoSVTkPWXd+tAXQj6Bi",
	"F6h1OwYdbD3uW6qnY8jezeniNiDE51V08evhAGoJIgIJ0TYeeekE//OQ87/22ScnfAzl6sf+IDDAIBGc",
	"nGeqZcE9JEk0MotTTLmFF1IBT89CEKUn9hC+QIdVH1BkdrHtTq2hmDpZWAfTApIE2yhvo8eRGYVKPcja",
	"xYFiAwUyyWW2qgTc5Chdzvh1IWcGmISPHz9Nliz5TiHb8FD/AFqzmknzINtcNTMWFsuj1awGW26F/mqt",
	"GTtPB7OkbiFmNbMyDKacmU9KY7gotZt5zBm1mz5OVNwuHFR5YJ8gzDcWS6qEA4jf2gZKXrpNj7PHXVMF",
	"SuxM84Jbvh5wi82NVhCwlc2MsbAWFiHcg+OAU5yo1WpieUE/mVJwO1luJo58wknKNgbugWWZxoxqxL1H",
	"PJPlBu5B+1/8Ekuc3Cj9He6hZMbYXKsqy48j9k7ZscFpLJcrFeCcUKwmuXI82Xtu/1ItO7rMakodfQ5t",
	"j6pW4KkHM53NzdQTD2YKjnig7453MFBWQmAK1JLCdZZfxy0qdTtrTu8YmKQeriGLJ54CbR0OKDNa1ubM",
	"gq20pKTe1J0ypr47JhCrKEo2JVIT5BLFEWkNHQEvyCkmR7QxoUGZVmUMSU6zhcpiWGqW0ei4KdjUBmsb",
	"g9K0oM2pHXf5YJpdOfzfBuMPI97bbwUEX2qmORpX5WsCLMq41ez7H/B69iGKozVqU18hnb88f+kwX4mS",
	"lTy6iP7t/NX5SwpxZnMX01NW8qnfpAt25bsizwxwJQng1DxNS7P4QEFjf1bp5ukuEgZk0HYYjwQsdu8x",
	"fnz58sDiKrFoJ8Zq9PcvgRuTJZfM3azsZsLoDuMqxzoSyGFc4LmnqNvWP7SxVll/R+JvPaqioDUbmwLr",
	"hRWFRxesupJn4EKRFiQtWWYoM2tvOTLQuc9hJ2eSDAM4Yo4+1nGNekORZblMbHerCqVGQwrw+sxz3ZXv",
	"4hKW5BjXN8MtqZRqVabqxrEhw0j5yI397NV5kLfGodKeIOPjc3hajJz1drBDQ1s0j/cX7WzHeF50zzO1",
	"IzrPuJvjnmPGxpq7EfHgZYg9mLQbMt13mb39+n9mdbeRXqOf8TVKb6cnMr7urcBq0T3je1v3bF/JfkXb",
	"0baSxqmZkkELLsmxSQAPuCNF1xnkKFQ0lfCEKp0QdWFukvgcFq7iGFhzBovFJby4RkMHFG6uYUUONGeg",
	"CG62GLOHR2q46V4iSXEXc5ZaGfTI8ydQNkd9ww16WoUVCAkTYqBrKRiX8NfF5186BUcpO69k2xc9T2Xv",
	"EW6PLusPW7m7GXB82a2durIWPBZ2L89oBCGUnv/In96H4KOGuUCo6+aKSybgbc/QJ50rGqW/wG1cFANy",
	"ci54LTEFZtzSStfe9T/1vYslSndJrSQFlpsejq29rcxjc3ReyWPg2r2A5A+0HuLq53Alexncp3v2FtCG",
	"NXpsDXXN/ZEpO++FnTBj8BbICeOH73k9upyfwI2ZQ+9uLNq2JG1Y3xtuc8ix0r5iOroTSnQs7LTU6jd3",
	"H/DYYHrr8X3c8cWYAnUHDZll6x6iFzwdiddF0EYm+2HtleZZhnpBg0aG/vHpDF3zhyH7bmQCLEmwtJj+",
	"RJDPNNWEkpNaOpk+3pr1RinvuUw0UpVhwvNx1BI3HVrbYPWtStYZWtSRd9X+tHyPtsdsPmcId6sEjPuR",
	"Gev36Po1y4oyBi4nZc0WwkqwLKbYrflJT00+3txvKq0dT0drm8YKewzaFMzDVe6qHfVUAO8U1vMU3Pda",
	"iLboPxXMbuXBC2qA7YRL+AGSylhVnPVM2dnu6zbek+RvHEP6zAhnhyb+3wU5nbfCAMNzxGlr1ScIcCcR",
	"WO2SVvIe14xCfZrV1737AfoXgwauUaDA4pqQUJXYiiCDqmxZWWqMawal3zObEhN4UXMofT7Fg5+zjmxZ",
	"8VsySTNkeoxwcZj9HJpemkGq2cqp4VkrR8FPDVvjTyCVp3i4OxgNd2zYsr6jJJA+BuG799/PFKf7rtn/",
	"ySK2CY8uZr25n6C8fPw0CcSNd6YLDgZ9fU4N6Duebn0QC7QBfvfnpox1pY1ppEgBN4Ut/ftpw6h466T1",
	"YuJhCDf0dnMAUv75wNWT30/6FICOBJ1cMuIoeCUWMGMilMSJkhN3B1aTtxJvmoUSVW5As7ojYhKKyrL2",
	"haj2eOGS+qkk4IQvZcqexQn/z46hytkxdTSnc1p69oRH0iV5n518EjXdw0HM1bUYz95Z7vzj4YQZof9L",
	"/VO0sDt/JjllxugfKM/a+A7uN0OI1v/jhhrN5qLK976Pj9IZy7ikLIhrDsS/G+//yzbuaNufvjo1Dep1",
	"E4JDlXs3QLB+FdVvFUfT9Stnylre3QlEOaTcJGrt2Bl3Ho5ee9/525NxHg5xwe3MEWXb+4NOaPqJVmr+",
	"D9P8Mhb0tndLOGleDvMswrohyEbyWhphLO9Dr3mmNnncQbvzp7tEcdcnPdHU+o3Fvpl/eQs/wMePn4BV",
	"NleaTqeV0rtg1PaawGbz7U+h3Qep7UnLxuEtJlUNcxqXVDLkT3YDSrfrd1RlfSnWza+/b79u/ycAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
