//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventType.
const (
	Commit  EventType = "commit"
	Issue   EventType = "issue"
	Pr      EventType = "pr"
	Release EventType = "release"
	Review  EventType = "review"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case Commit:
		return true
	case Issue:
		return true
	case Pr:
		return true
	case Release:
		return true
	case Review:
		return true
	default:
		return false
	}
}

// Defines values for ExportFormat.
const (
	Csv  ExportFormat = "csv"
	Json ExportFormat = "json"
	Pdf  ExportFormat = "pdf"
)

// Valid indicates whether the value is a known member of the ExportFormat enum.
func (e ExportFormat) Valid() bool {
	switch e {
	case Csv:
		return true
	case Json:
		return true
	case Pdf:
		return true
	default:
		return false
	}
}

// Block One display building block.
type Block struct {
	// Data Block-type-specific payload.
	Data map[string]interface{} `json:"data"`

	// Type heading | text | list | table | keyvalue | metric | code | chart.
	Type string `json:"type"`
}

// Document An ordered list of display blocks.
type Document = []Block

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Machine-readable error code, UPPER_SNAKE_CASE.
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// Event A single ingested activity event.
type Event struct {
	Additions *int    `json:"additions,omitempty"`
	Branch    *string `json:"branch,omitempty"`
	Deletions *int    `json:"deletions,omitempty"`

	// Id Stable id: "{type}:{owner}/{repo}:{sha|number}".
	Id string `json:"id"`

	// Number PR/issue number.
	Number *int    `json:"number,omitempty"`
	Owner  string  `json:"owner"`
	Repo   string  `json:"repo"`
	Sha    *string `json:"sha,omitempty"`

	// Title Commit subject / PR title.
	Title *string `json:"title,omitempty"`

	// Ts Unix seconds.
	Ts   int64     `json:"ts"`
	Type EventType `json:"type"`
	Url  *string   `json:"url,omitempty"`
}

// EventType defines model for EventType.
type EventType string

// ExportFormat defines model for ExportFormat.
type ExportFormat string

// ExportRequest defines model for ExportRequest.
type ExportRequest struct {
	// Document An ordered list of display blocks.
	Document *Document `json:"document,omitempty"`

	// Filter Timeline filter selecting the range/scope to operate on.
	Filter     *Filter                 `json:"filter,omitempty"`
	FormValues *map[string]interface{} `json:"formValues,omitempty"`
	Format     ExportFormat            `json:"format"`
	TemplateId *string                 `json:"templateId,omitempty"`
}

// Filter Timeline filter selecting the range/scope to operate on.
type Filter struct {
	From  *int64     `json:"from,omitempty"`
	Owner *string    `json:"owner,omitempty"`
	Repo  *string    `json:"repo,omitempty"`
	To    *int64     `json:"to,omitempty"`
	Type  *EventType `json:"type,omitempty"`
}

// FormField One input field a template's form collects on run.
type FormField struct {
	// Default Default value, if any. Shape matches `type`.
	Default  interface{} `json:"default,omitempty"`
	Label    *string     `json:"label,omitempty"`
	Name     string      `json:"name"`
	Required *bool       `json:"required,omitempty"`

	// Type Form field kind, e.g. string, number, boolean, date, select.
	Type string `json:"type"`
}

// GenerateTemplateRequest defines model for GenerateTemplateRequest.
type GenerateTemplateRequest struct {
	Prompt string `json:"prompt"`
}

// LLMModel defines model for LLMModel.
type LLMModel struct {
	ContextSize int    `json:"contextSize"`
	Id          string `json:"id"`

	// MaxReasoningEffort Highest supported reasoning effort, or "" when none.
	MaxReasoningEffort      string `json:"maxReasoningEffort"`
	SupportsReasoningEffort bool   `json:"supportsReasoningEffort"`

	// SupportsSamplingParams Whether the model accepts temperature and top-p.
	SupportsSamplingParams bool `json:"supportsSamplingParams"`
}

// LLMSettings defines model for LLMSettings.
type LLMSettings struct {
	Model           string   `json:"model"`
	ReasoningEffort *string  `json:"reasoningEffort,omitempty"`
	Temperature     *float32 `json:"temperature,omitempty"`
}

// LLMSettingsInput defines model for LLMSettingsInput.
type LLMSettingsInput struct {
	Model           string   `json:"model"`
	ReasoningEffort *string  `json:"reasoningEffort,omitempty"`
	Temperature     *float32 `json:"temperature,omitempty"`
}

// RunRequest defines model for RunRequest.
type RunRequest struct {
	// Filter Timeline filter selecting the range/scope to operate on.
	Filter *Filter `json:"filter,omitempty"`

	// FormValues Values keyed by the template's form field names.
	FormValues *map[string]interface{} `json:"formValues,omitempty"`
	TemplateId string                  `json:"templateId"`
}

// Session A derived cluster of events (per owner) whose inter-event gaps are all under the sessionization threshold.
type Session struct {
	// Day Owner-local calendar day this session is grouped under.
	Day *openapi_types.Date `json:"day,omitempty"`

	// DurationHours (endTs - startTs) + lead-in padding, in hours.
	DurationHours float64 `json:"durationHours"`
	EndTs         int64   `json:"endTs"`
	Events        []Event `json:"events"`
	Owner         string  `json:"owner"`
	StartTs       int64   `json:"startTs"`
}

// SessionsResponse defines model for SessionsResponse.
type SessionsResponse struct {
	Sessions []Session `json:"sessions"`
}

// SyncJob defines model for SyncJob.
type SyncJob struct {
	JobId string `json:"jobId"`
}

// SyncStatus defines model for SyncStatus.
type SyncStatus struct {
	InProgress bool `json:"inProgress"`

	// LastSyncedTs Unix seconds of the most recent completed sync.
	LastSyncedTs int64 `json:"lastSyncedTs"`

	// PerOwner Per-owner sync counts/state, keyed by owner name.
	PerOwner map[string]interface{} `json:"perOwner"`
}

// Template defines model for Template.
type Template struct {
	Description *string        `json:"description,omitempty"`
	Exports     []ExportFormat `json:"exports"`
	Form        []FormField    `json:"form"`
	Id          string         `json:"id"`
	Layout      []Block        `json:"layout"`

	// Model Only meaningful when the layout has an LLM-backed block.
	Model     *string         `json:"model,omitempty"`
	Name      string          `json:"name"`
	Transform []TransformStep `json:"transform"`
}

// TemplateInput Template fields a client submits on create/edit (no id).
type TemplateInput struct {
	Description *string        `json:"description,omitempty"`
	Exports     []ExportFormat `json:"exports"`
	Form        []FormField    `json:"form"`
	Layout      []Block        `json:"layout"`

	// Model Only meaningful when the layout has an LLM-backed block.
	Model     *string         `json:"model,omitempty"`
	Name      string          `json:"name"`
	Transform []TransformStep `json:"transform"`
}

// TimelinePage defines model for TimelinePage.
type TimelinePage struct {
	HasMore bool    `json:"hasMore"`
	Items   []Event `json:"items"`
}

// TransformStep One step of a template's transform pipeline.
type TransformStep struct {
	// Params Primitive-specific parameters.
	Params *map[string]interface{} `json:"params,omitempty"`

	// Primitive sessionize | exclude-off-time | split-by-active-days | aggregate | group-by | rate | describe-work | passthrough.
	Primitive string `json:"primitive"`
}

// EventTypeQueryParam defines model for EventTypeQueryParam.
type EventTypeQueryParam = EventType

// FromQueryParam defines model for FromQueryParam.
type FromQueryParam = int64

// GapQueryParam defines model for GapQueryParam.
type GapQueryParam = int64

// OwnerQueryParam defines model for OwnerQueryParam.
type OwnerQueryParam = string

// OwnerQueryParamRequired defines model for OwnerQueryParamRequired.
type OwnerQueryParamRequired = string

// PageQueryParam defines model for PageQueryParam.
type PageQueryParam = int

// PerPageQueryParam defines model for PerPageQueryParam.
type PerPageQueryParam = int

// RepoQueryParam defines model for RepoQueryParam.
type RepoQueryParam = string

// TemplateIdPathParam defines model for TemplateIdPathParam.
type TemplateIdPathParam = string

// ToQueryParam defines model for ToQueryParam.
type ToQueryParam = int64

// Error defines model for Error.
type Error = ErrorResponse

// ListReposParams defines parameters for ListRepos.
type ListReposParams struct {
	// Owner Owner/org to list repos for.
	Owner OwnerQueryParamRequired `form:"owner" json:"owner"`
}

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	// Owner Filter by owner/org.
	Owner *OwnerQueryParam `form:"owner,omitempty" json:"owner,omitempty"`

	// From Range start, unix seconds (inclusive).
	From *FromQueryParam `form:"from,omitempty" json:"from,omitempty"`

	// To Range end, unix seconds (exclusive).
	To *ToQueryParam `form:"to,omitempty" json:"to,omitempty"`

	// Gap Inter-event gap threshold, in seconds, overriding GITRAKZ_SESSION_GAP for this request's sessionization.
	Gap *GapQueryParam `form:"gap,omitempty" json:"gap,omitempty"`
}

// ListTimelineParams defines parameters for ListTimeline.
type ListTimelineParams struct {
	// Owner Filter by owner/org.
	Owner *OwnerQueryParam `form:"owner,omitempty" json:"owner,omitempty"`

	// Repo Filter by repo.
	Repo *RepoQueryParam `form:"repo,omitempty" json:"repo,omitempty"`

	// Type Filter by event type.
	Type *EventTypeQueryParam `form:"type,omitempty" json:"type,omitempty"`

	// From Range start, unix seconds (inclusive).
	From *FromQueryParam `form:"from,omitempty" json:"from,omitempty"`

	// To Range end, unix seconds (exclusive).
	To *ToQueryParam `form:"to,omitempty" json:"to,omitempty"`

	// Page 1-indexed page number.
	Page *PageQueryParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Page size.
	PerPage *PerPageQueryParam `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// ExportDocumentJSONRequestBody defines body for ExportDocument for application/json ContentType.
type ExportDocumentJSONRequestBody = ExportRequest

// UpdateLLMSettingsJSONRequestBody defines body for UpdateLLMSettings for application/json ContentType.
type UpdateLLMSettingsJSONRequestBody = LLMSettingsInput

// RunTemplateJSONRequestBody defines body for RunTemplate for application/json ContentType.
type RunTemplateJSONRequestBody = RunRequest

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = TemplateInput

// GenerateTemplateJSONRequestBody defines body for GenerateTemplate for application/json ContentType.
type GenerateTemplateJSONRequestBody = GenerateTemplateRequest

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody = TemplateInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ExportDocument Export a document (or a template run) to a file
	// (POST /export)
	ExportDocument(w http.ResponseWriter, r *http.Request)
	// ListLLMModels List available LLM models with capabilities
	// (GET /llm/models)
	ListLLMModels(w http.ResponseWriter, r *http.Request)
	// GetLLMSettings Get the current LLM settings
	// (GET /llm/settings)
	GetLLMSettings(w http.ResponseWriter, r *http.Request)
	// UpdateLLMSettings Update the LLM settings
	// (PUT /llm/settings)
	UpdateLLMSettings(w http.ResponseWriter, r *http.Request)
	// ListOwners List distinct owners/orgs
	// (GET /owners)
	ListOwners(w http.ResponseWriter, r *http.Request)
	// ListRepos List repos under an owner
	// (GET /repos)
	ListRepos(w http.ResponseWriter, r *http.Request, params ListReposParams)
	// RunTemplate Run a template's transform pipeline over a filtered range
	// (POST /run)
	RunTemplate(w http.ResponseWriter, r *http.Request)
	// ListSessions Derived, sessionized view of the timeline
	// (GET /sessions)
	ListSessions(w http.ResponseWriter, r *http.Request, params ListSessionsParams)
	// TriggerSync Trigger an incremental sync of activity from `gh`
	// (POST /sync)
	TriggerSync(w http.ResponseWriter, r *http.Request)
	// GetSyncStatus Current sync status
	// (GET /sync/status)
	GetSyncStatus(w http.ResponseWriter, r *http.Request)
	// ListTemplates List templates (built-in + custom)
	// (GET /templates)
	ListTemplates(w http.ResponseWriter, r *http.Request)
	// CreateTemplate Create a custom template
	// (POST /templates)
	CreateTemplate(w http.ResponseWriter, r *http.Request)
	// GenerateTemplate LLM-compose a template draft from a description
	// (POST /templates/generate)
	GenerateTemplate(w http.ResponseWriter, r *http.Request)
	// DeleteTemplate Delete a custom template
	// (DELETE /templates/{id})
	DeleteTemplate(w http.ResponseWriter, r *http.Request, id TemplateIdPathParam)
	// UpdateTemplate Edit a template
	// (PUT /templates/{id})
	UpdateTemplate(w http.ResponseWriter, r *http.Request, id TemplateIdPathParam)
	// ListTimeline Paginated, filterable event timeline
	// (GET /timeline)
	ListTimeline(w http.ResponseWriter, r *http.Request, params ListTimelineParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ExportDocument operation middleware
func (siw *ServerInterfaceWrapper) ExportDocument(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportDocument(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLLMModels operation middleware
func (siw *ServerInterfaceWrapper) ListLLMModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLLMModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLLMSettings operation middleware
func (siw *ServerInterfaceWrapper) GetLLMSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLLMSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLLMSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateLLMSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLLMSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOwners operation middleware
func (siw *ServerInterfaceWrapper) ListOwners(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOwners(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepos operation middleware
func (siw *ServerInterfaceWrapper) ListRepos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReposParams

	// ------------- Required query parameter "owner" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunTemplate operation middleware
func (siw *ServerInterfaceWrapper) RunTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSessionsParams

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "gap" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "gap", r.URL.Query(), &params.Gap, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "gap"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gap", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerSync(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSyncStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSyncStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSyncStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListTemplates(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTemplates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateTemplate operation middleware
func (siw *ServerInterfaceWrapper) GenerateTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTemplate operation middleware
func (siw *ServerInterfaceWrapper) DeleteTemplate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TemplateIdPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTemplate operation middleware
func (siw *ServerInterfaceWrapper) UpdateTemplate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TemplateIdPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTimeline operation middleware
func (siw *ServerInterfaceWrapper) ListTimeline(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTimelineParams

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "repo" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "repo", r.URL.Query(), &params.Repo, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "repo"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "per_page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTimeline(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/owners", wrapper.ListOwners)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos", wrapper.ListRepos)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/timeline", wrapper.ListTimeline)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions", wrapper.ListSessions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sync", wrapper.TriggerSync)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sync/status", wrapper.GetSyncStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/templates", wrapper.ListTemplates)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/templates", wrapper.CreateTemplate)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/templates/{id}", wrapper.DeleteTemplate)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/templates/{id}", wrapper.UpdateTemplate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/templates/generate", wrapper.GenerateTemplate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/run", wrapper.RunTemplate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/export", wrapper.ExportDocument)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/llm/models", wrapper.ListLLMModels)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/llm/settings", wrapper.GetLLMSettings)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/llm/settings", wrapper.UpdateLLMSettings)

	return m
}

type ErrorJSONResponse ErrorResponse

type ExportDocumentRequestObject struct {
	Body *ExportDocumentJSONRequestBody
}

type ExportDocumentResponseObject interface {
	VisitExportDocumentResponse(w http.ResponseWriter) error
}

type ExportDocument200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ExportDocument200ApplicationoctetStreamResponse) VisitExportDocumentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExportDocumentdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ExportDocumentdefaultJSONResponse) VisitExportDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListLLMModelsRequestObject struct {
}

type ListLLMModelsResponseObject interface {
	VisitListLLMModelsResponse(w http.ResponseWriter) error
}

type ListLLMModels200JSONResponse []LLMModel

func (response ListLLMModels200JSONResponse) VisitListLLMModelsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLLMModelsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListLLMModelsdefaultJSONResponse) VisitListLLMModelsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetLLMSettingsRequestObject struct {
}

type GetLLMSettingsResponseObject interface {
	VisitGetLLMSettingsResponse(w http.ResponseWriter) error
}

type GetLLMSettings200JSONResponse LLMSettings

func (response GetLLMSettings200JSONResponse) VisitGetLLMSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLLMSettingsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetLLMSettingsdefaultJSONResponse) VisitGetLLMSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLLMSettingsRequestObject struct {
	Body *UpdateLLMSettingsJSONRequestBody
}

type UpdateLLMSettingsResponseObject interface {
	VisitUpdateLLMSettingsResponse(w http.ResponseWriter) error
}

type UpdateLLMSettings200JSONResponse LLMSettings

func (response UpdateLLMSettings200JSONResponse) VisitUpdateLLMSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLLMSettingsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response UpdateLLMSettingsdefaultJSONResponse) VisitUpdateLLMSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnersRequestObject struct {
}

type ListOwnersResponseObject interface {
	VisitListOwnersResponse(w http.ResponseWriter) error
}

type ListOwners200JSONResponse []string

func (response ListOwners200JSONResponse) VisitListOwnersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnersdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListOwnersdefaultJSONResponse) VisitListOwnersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListReposRequestObject struct {
	Params ListReposParams
}

type ListReposResponseObject interface {
	VisitListReposResponse(w http.ResponseWriter) error
}

type ListRepos200JSONResponse []string

func (response ListRepos200JSONResponse) VisitListReposResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListReposdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListReposdefaultJSONResponse) VisitListReposResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RunTemplateRequestObject struct {
	Body *RunTemplateJSONRequestBody
}

type RunTemplateResponseObject interface {
	VisitRunTemplateResponse(w http.ResponseWriter) error
}

type RunTemplate200JSONResponse Document

func (response RunTemplate200JSONResponse) VisitRunTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RunTemplatedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response RunTemplatedefaultJSONResponse) VisitRunTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessionsRequestObject struct {
	Params ListSessionsParams
}

type ListSessionsResponseObject interface {
	VisitListSessionsResponse(w http.ResponseWriter) error
}

type ListSessions200JSONResponse SessionsResponse

func (response ListSessions200JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessionsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListSessionsdefaultJSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSyncRequestObject struct {
}

type TriggerSyncResponseObject interface {
	VisitTriggerSyncResponse(w http.ResponseWriter) error
}

type TriggerSync202JSONResponse SyncJob

func (response TriggerSync202JSONResponse) VisitTriggerSyncResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSyncdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response TriggerSyncdefaultJSONResponse) VisitTriggerSyncResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSyncStatusRequestObject struct {
}

type GetSyncStatusResponseObject interface {
	VisitGetSyncStatusResponse(w http.ResponseWriter) error
}

type GetSyncStatus200JSONResponse SyncStatus

func (response GetSyncStatus200JSONResponse) VisitGetSyncStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSyncStatusdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetSyncStatusdefaultJSONResponse) VisitGetSyncStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListTemplatesRequestObject struct {
}

type ListTemplatesResponseObject interface {
	VisitListTemplatesResponse(w http.ResponseWriter) error
}

type ListTemplates200JSONResponse []Template

func (response ListTemplates200JSONResponse) VisitListTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTemplatesdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListTemplatesdefaultJSONResponse) VisitListTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTemplateRequestObject struct {
	Body *CreateTemplateJSONRequestBody
}

type CreateTemplateResponseObject interface {
	VisitCreateTemplateResponse(w http.ResponseWriter) error
}

type CreateTemplate200JSONResponse Template

func (response CreateTemplate200JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTemplatedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CreateTemplatedefaultJSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateTemplateRequestObject struct {
	Body *GenerateTemplateJSONRequestBody
}

type GenerateTemplateResponseObject interface {
	VisitGenerateTemplateResponse(w http.ResponseWriter) error
}

type GenerateTemplate200JSONResponse Template

func (response GenerateTemplate200JSONResponse) VisitGenerateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateTemplatedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GenerateTemplatedefaultJSONResponse) VisitGenerateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTemplateRequestObject struct {
	Id TemplateIdPathParam `json:"id"`
}

type DeleteTemplateResponseObject interface {
	VisitDeleteTemplateResponse(w http.ResponseWriter) error
}

type DeleteTemplate204Response struct {
}

func (response DeleteTemplate204Response) VisitDeleteTemplateResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTemplatedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response DeleteTemplatedefaultJSONResponse) VisitDeleteTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTemplateRequestObject struct {
	Id   TemplateIdPathParam `json:"id"`
	Body *UpdateTemplateJSONRequestBody
}

type UpdateTemplateResponseObject interface {
	VisitUpdateTemplateResponse(w http.ResponseWriter) error
}

type UpdateTemplate200JSONResponse Template

func (response UpdateTemplate200JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTemplatedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response UpdateTemplatedefaultJSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListTimelineRequestObject struct {
	Params ListTimelineParams
}

type ListTimelineResponseObject interface {
	VisitListTimelineResponse(w http.ResponseWriter) error
}

type ListTimeline200JSONResponse TimelinePage

func (response ListTimeline200JSONResponse) VisitListTimelineResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTimelinedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListTimelinedefaultJSONResponse) VisitListTimelineResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ExportDocument Export a document (or a template run) to a file
	// (POST /export)
	ExportDocument(ctx context.Context, request ExportDocumentRequestObject) (ExportDocumentResponseObject, error)
	// ListLLMModels List available LLM models with capabilities
	// (GET /llm/models)
	ListLLMModels(ctx context.Context, request ListLLMModelsRequestObject) (ListLLMModelsResponseObject, error)
	// GetLLMSettings Get the current LLM settings
	// (GET /llm/settings)
	GetLLMSettings(ctx context.Context, request GetLLMSettingsRequestObject) (GetLLMSettingsResponseObject, error)
	// UpdateLLMSettings Update the LLM settings
	// (PUT /llm/settings)
	UpdateLLMSettings(ctx context.Context, request UpdateLLMSettingsRequestObject) (UpdateLLMSettingsResponseObject, error)
	// ListOwners List distinct owners/orgs
	// (GET /owners)
	ListOwners(ctx context.Context, request ListOwnersRequestObject) (ListOwnersResponseObject, error)
	// ListRepos List repos under an owner
	// (GET /repos)
	ListRepos(ctx context.Context, request ListReposRequestObject) (ListReposResponseObject, error)
	// RunTemplate Run a template's transform pipeline over a filtered range
	// (POST /run)
	RunTemplate(ctx context.Context, request RunTemplateRequestObject) (RunTemplateResponseObject, error)
	// ListSessions Derived, sessionized view of the timeline
	// (GET /sessions)
	ListSessions(ctx context.Context, request ListSessionsRequestObject) (ListSessionsResponseObject, error)
	// TriggerSync Trigger an incremental sync of activity from `gh`
	// (POST /sync)
	TriggerSync(ctx context.Context, request TriggerSyncRequestObject) (TriggerSyncResponseObject, error)
	// GetSyncStatus Current sync status
	// (GET /sync/status)
	GetSyncStatus(ctx context.Context, request GetSyncStatusRequestObject) (GetSyncStatusResponseObject, error)
	// ListTemplates List templates (built-in + custom)
	// (GET /templates)
	ListTemplates(ctx context.Context, request ListTemplatesRequestObject) (ListTemplatesResponseObject, error)
	// CreateTemplate Create a custom template
	// (POST /templates)
	CreateTemplate(ctx context.Context, request CreateTemplateRequestObject) (CreateTemplateResponseObject, error)
	// GenerateTemplate LLM-compose a template draft from a description
	// (POST /templates/generate)
	GenerateTemplate(ctx context.Context, request GenerateTemplateRequestObject) (GenerateTemplateResponseObject, error)
	// DeleteTemplate Delete a custom template
	// (DELETE /templates/{id})
	DeleteTemplate(ctx context.Context, request DeleteTemplateRequestObject) (DeleteTemplateResponseObject, error)
	// UpdateTemplate Edit a template
	// (PUT /templates/{id})
	UpdateTemplate(ctx context.Context, request UpdateTemplateRequestObject) (UpdateTemplateResponseObject, error)
	// ListTimeline Paginated, filterable event timeline
	// (GET /timeline)
	ListTimeline(ctx context.Context, request ListTimelineRequestObject) (ListTimelineResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ExportDocument operation middleware
func (sh *strictHandler) ExportDocument(w http.ResponseWriter, r *http.Request) {
	var request ExportDocumentRequestObject

	var body ExportDocumentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportDocument(ctx, request.(ExportDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportDocumentResponseObject); ok {
		if err := validResponse.VisitExportDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListLLMModels operation middleware
func (sh *strictHandler) ListLLMModels(w http.ResponseWriter, r *http.Request) {
	var request ListLLMModelsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListLLMModels(ctx, request.(ListLLMModelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLLMModels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListLLMModelsResponseObject); ok {
		if err := validResponse.VisitListLLMModelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLLMSettings operation middleware
func (sh *strictHandler) GetLLMSettings(w http.ResponseWriter, r *http.Request) {
	var request GetLLMSettingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLLMSettings(ctx, request.(GetLLMSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLLMSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLLMSettingsResponseObject); ok {
		if err := validResponse.VisitGetLLMSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateLLMSettings operation middleware
func (sh *strictHandler) UpdateLLMSettings(w http.ResponseWriter, r *http.Request) {
	var request UpdateLLMSettingsRequestObject

	var body UpdateLLMSettingsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateLLMSettings(ctx, request.(UpdateLLMSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateLLMSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateLLMSettingsResponseObject); ok {
		if err := validResponse.VisitUpdateLLMSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOwners operation middleware
func (sh *strictHandler) ListOwners(w http.ResponseWriter, r *http.Request) {
	var request ListOwnersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOwners(ctx, request.(ListOwnersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOwners")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOwnersResponseObject); ok {
		if err := validResponse.VisitListOwnersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRepos operation middleware
func (sh *strictHandler) ListRepos(w http.ResponseWriter, r *http.Request, params ListReposParams) {
	var request ListReposRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRepos(ctx, request.(ListReposRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRepos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListReposResponseObject); ok {
		if err := validResponse.VisitListReposResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RunTemplate operation middleware
func (sh *strictHandler) RunTemplate(w http.ResponseWriter, r *http.Request) {
	var request RunTemplateRequestObject

	var body RunTemplateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunTemplate(ctx, request.(RunTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunTemplateResponseObject); ok {
		if err := validResponse.VisitRunTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSessions operation middleware
func (sh *strictHandler) ListSessions(w http.ResponseWriter, r *http.Request, params ListSessionsParams) {
	var request ListSessionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSessions(ctx, request.(ListSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSessionsResponseObject); ok {
		if err := validResponse.VisitListSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerSync operation middleware
func (sh *strictHandler) TriggerSync(w http.ResponseWriter, r *http.Request) {
	var request TriggerSyncRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerSync(ctx, request.(TriggerSyncRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerSync")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerSyncResponseObject); ok {
		if err := validResponse.VisitTriggerSyncResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSyncStatus operation middleware
func (sh *strictHandler) GetSyncStatus(w http.ResponseWriter, r *http.Request) {
	var request GetSyncStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSyncStatus(ctx, request.(GetSyncStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSyncStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSyncStatusResponseObject); ok {
		if err := validResponse.VisitGetSyncStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTemplates operation middleware
func (sh *strictHandler) ListTemplates(w http.ResponseWriter, r *http.Request) {
	var request ListTemplatesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTemplates(ctx, request.(ListTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTemplates")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTemplatesResponseObject); ok {
		if err := validResponse.VisitListTemplatesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTemplate operation middleware
func (sh *strictHandler) CreateTemplate(w http.ResponseWriter, r *http.Request) {
	var request CreateTemplateRequestObject

	var body CreateTemplateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTemplate(ctx, request.(CreateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTemplateResponseObject); ok {
		if err := validResponse.VisitCreateTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateTemplate operation middleware
func (sh *strictHandler) GenerateTemplate(w http.ResponseWriter, r *http.Request) {
	var request GenerateTemplateRequestObject

	var body GenerateTemplateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateTemplate(ctx, request.(GenerateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateTemplateResponseObject); ok {
		if err := validResponse.VisitGenerateTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTemplate operation middleware
func (sh *strictHandler) DeleteTemplate(w http.ResponseWriter, r *http.Request, id TemplateIdPathParam) {
	var request DeleteTemplateRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTemplate(ctx, request.(DeleteTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTemplateResponseObject); ok {
		if err := validResponse.VisitDeleteTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTemplate operation middleware
func (sh *strictHandler) UpdateTemplate(w http.ResponseWriter, r *http.Request, id TemplateIdPathParam) {
	var request UpdateTemplateRequestObject

	request.Id = id

	var body UpdateTemplateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTemplate(ctx, request.(UpdateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTemplate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTemplateResponseObject); ok {
		if err := validResponse.VisitUpdateTemplateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTimeline operation middleware
func (sh *strictHandler) ListTimeline(w http.ResponseWriter, r *http.Request, params ListTimelineParams) {
	var request ListTimelineRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTimeline(ctx, request.(ListTimelineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTimeline")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTimelineResponseObject); ok {
		if err := validResponse.VisitListTimelineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fvrchy3cn6VrkmqDlWe5UrOSX7Qv2TdrHMoiyGppCq2SsIOemdgYYAxgFlyTbIqD5EnzJOkGpjrDvZC",
	"k3Jcdf6RO7g0vm705euZmyTTZaUVKmeTk5ukYoaV6ND4/16tULnLdYX/XqNZn9Ez+pmjzYyonNAqOUle",
	"C+nQwGINSMPBrSs8TtJE0MNfaWKSJoqVmJwk9CxJE5sVWDJa6p8NLpOT5J/mvRjz8NTOu92Tu7s0eW10",
	"uUuMc6ZyBOuYcSnUSlyDxUwrbuFIqEzWVqzwyTa5lkaXI7mW2pTMJSeJUO7f/pqkQXL/L+ZovERvWLVL",
	"oLfKoZkFTHJWgSsM2kJLnoJQrXAp6BUaI7hQObx5e3n+/O//9eni1cXF2/c/fnrz/AyW2oArhAWDv9Zo",
	"3V8sWLRWaCV+Y7TTtiPlrLr3id5fKTSH6VrT0Lk2+bb9/YCRBM2G1hmh8th+5/hrLQzy6b7v293AaZDC",
	"OjBYaUvo7NvfdIs6U+Nuec5YvtPUn82E4niNHCqWI6i6XOBWAWjI6Pwcl6yWLjl5lialUKKsS/93RBFn",
	"aPbJQs/Bit+23rUKzaftMvzr0zQp2XUQ4tunT/eKdI6VPsw0SDXbhKJne4ziEstKModv+RlzRbebX61i",
	"rugXE/ye+r3U+z0IKr7pP/B6n/9w+p537Y4Et5VWFoOnNUYb+iPTyqFy9CerKikyf8nnv1gS8eZQz0mr",
	"nTfrh93GR32uAGkM6CyrjUF+7PFp5tPy30udfYlcRIXAha0kW8OiFtL7rQWNJWgqoys0ToQzcebYdAW/",
	"8IwAmdkKM7EUGVRsLTXjxz1SevELZi65a3/YXKVA5re+BYfXDm6DU7gFxxYS4Ra+4HrFZE1/luiMyOAW",
	"Ms3p/6xgxg22GthHb0s/taHKH+JjRK6XOqvLRlMTcLXhaJAHqfSyh4wOb70VOSztPj0GJXQgJMwYtqb/",
	"xwqmuD1Cnk46lesdywqhcGaQcQ9TMAEanMKHs7NX558ufnz+91efXjy/eBUBiIzIMSFtf7l+agFJE1VL",
	"mXy8S5MSrSW3E72BQ4S9lP34GMg+BYggDFaoXCIIlaN1yIFlTqyEa3KQqS0yzgVNHsneXseB8AvDVFYM",
	"BzXCD8ZwlHjIWiISyC6CgQp+Aj8nNzT57uTGh6q7+Q05x7uTG1uw2xBa7n5OonoITyMx4XwurK2HkWmH",
	"fCFCTtWUBi8de2ALthsbJ5yMmN4LXZbCga29ZmEOZ+fghw5FjKxmp0t9GLhmmr3X1/Yu5MBkM01qI0du",
	"vDZih5wbZu2jkrPthHSQiVR6u5VfNkKiohhMt4Mg84bs564EXpHfIP36HyQyO7w1vZZeXVfauNeN9IMl",
	"7YrW48skTXxA2T75PGSbU9fCB25vF56de7xLk6VPDfbNCAmEH69N+R/kvUdXl8mzgSQh2E+gXHaH3qns",
	"IUBkIF3Ksd9rNTvE9Pi6O+fYZC9FiVIohAAEWJSYOQpfrkAwlHbMbaYrpOyWjsgcQsjsx+D7MuWQ/OJ3",
	"XW6nD1z7nvfpLgaVNuVrgZLHUwyhqtrBkgYAg1Y9f/EJfwmZlgSgBa3A1BGcuix3c+2X4QH43CAFsQSm",
	"1sdwUbAKoWQuK9DCZ5L28zGJKdkC5W6PFzLAKM7DaqYRaMmk7e12obVEpranOQRTA8MXQYkpHufHEPZI",
	"Gy+fQrNMCpw5TBvz2p/heMmbQTFzfoPKm2KbkG/1CZXRZeX2X51mXGyv09N37zQPWG/mMopSvAvx2xDm",
	"gTUKHoW/ZNfnyKxWQuWvlkttIubwg8gLtBSXKnIIyMG0UwD9nBS0gZ+TnxO4KlCB0gqjEblZwUa2nOq6",
	"HXzBykoKlft6JBLq/rNAV6DxXqIkdIBlGVbO+htBuqkNAlMcnK5m1UCwbrNYbNomaxSzrdKmI81s0ekF",
	"OvJzdqrWstV25N5sg3DgqvrzD543adHmocNWeyR8Sx7nTyrmea223r2vF1vHthjmUF2FnIp8sslNvxwc",
	"FbkVGy/l7hFmB2NjkFwEDixWGnA0YoUcqGanaKuXoSiwcFTRvxQYn8BVoS3FmRFHZ4HRhZISasWbizdm",
	"23oWL1bvrrcwVzOpMyYhYxIVZwY4WwdSr1kchIXc6LpCHnYeJbbk1aPVWG28TD/o2kS8xxEqfmlhFjjR",
	"S/sEvgGJjM+EgooUTyFEKCho+nhDXS/kYMvWYNPEL3lglhBA99TNIbVuKPUite72TKY52KHs5tC8Onay",
	"WaI92iaq3TF2GKHdXog3+j0chdauJzhsyN8tHJVrrbK/6cVUnF/04pC7F4ZtW/nCMVdHPLpQZ0bnBq2N",
	"Rz3JrKP52JjQ9rKOrmyIeZ7ozeh2ElYSKUTbtcoOLPwqNO9b6znc1Z2hmXn78FtBpmuvIeeTq84BhhHk",
	"7CK+bgPQ0dHTIVIDGWN4t6mXP4CU75fJyU+7DahjT308u0snWjpA/yKm/I9DarYNlht1TvM4BAILDDIp",
	"SHm2XpQi5OuZQeZwjlw4OFIaBH8Sy98Hy+5KvtEXcvdwMpuF34avIZs6eLG+homsJNlaB4wexvR1Cchm",
	"kSTXUCKjBGRZy5Cd0p0J+0LBLDAFp6fvZguWfSGTbUna31HKOMOUvRc2l+2MC4fVXm/WVCJ+h+FuHYy9",
	"pqO3pKmvzxracWxMBbPv9CgBGzil7jAPiVGb18cvlXYbR0Ue4ROtga3DijzhqP7tsIFKVP7Q09tTbSkn",
	"zowohROrEfHetnujCVvVzpgu1qVFCLfgGyQcZ3q5nDlR0k+2ksLNFuuZZ2Zxxtnawi2wPDeYk4+4DRnP",
	"bLGGWzDhl7DFAmdX2nyBW6iYta4wus6L/eVsL+wUcBor1FJHCFmUy1mhPYn8Rrgf6kXPJTtDV8ccQ0fg",
	"6CUEXs7Oz87tPLBydg6elaP/PSlnoaqlRA5Lo0v4nBef0y4r9Sdro3fqizfWdVJmoT/QKRxQ5bStK5gD",
	"VxtFl3rd0EhUrfqOlVBOk5WsK+QphIviWeaWq4MjUootEF1K2aDidZVCVtBsqfMUFoblNDptHbbBqi1+",
	"mVq7ggpifx9seyqf/3fG+M2kKRSOAlIsDDMCrffyDTuc5MIZ9uU3eH72NkmTFRrb9FePnx4/9TlfhYpV",
	"IjlJ/uX42fFTMnHmCm/T83BAb+g6VESBMhNaUXLTEJgd/xiMBK37XvP143XYRizp3dgWKanYbPB9+/Tp",
	"js115tDNrDMYGpORVuJCKOZbjpu3YNLcuyywsQJSlpB4HHo3HScWO1gnbGgehnZgXZa0Z4spsIFJkWn0",
	"hmpq9QS8GdKGJCWjqv+nxm8HlnwuZTn3Ac1DkmNEe6fCupYMssm9QJxq8CCn3lFPU78+7ZuumJD+boVj",
	"BPKlQGEgYxVbCEl+YylZbh8OOkEBrNvx9PRdu+uVcEW/Ibn9HnApywHadkDARPF+g27I0zwQ8D04d9ts",
	"sVrrNLk1Omkr+MNhfIPOeyvf6FZutPoEtzRpMtsxSh8qKsI3gXp8tzIhpB7sWR5dR7WH4rGVFAD2etqp",
	"H7JrX3kNLXrjNQ4MkRJXaNYUl5xQmetfWILKoCVDEE3G7LmZwAFlLCswbV666vo13OiK6yvfaJh6q/dB",
	"nMdyVdPke49Pejk6oaUjPpbz4ZGlByppFBG04l/I2unWz/2IdPSO4ZZqth8y3/aO2N3H/zfE/UEGFGEu",
	"VqgCRo8EvBnswJqlB8AHrBvcazXMhTYkrZX1InICsxSKFJpFqggfyExzc3xXEm0tQ4+S8somnevCP7Pw",
	"t4v3Px7Dc7UeVpmV0RZDrQnC+pyx9qQNmhWamRUc4Yj28jfNEymhKzTPtFqKHJpk8IkXyL+4yZG3VzUI",
	"iLyX43//+3/8k6tCDxPeTJdogWSiqVr583jQp3f4vFYdzfJ1vPqAv/+D/XnfhY87c4MqvKgUU/LDbfm8",
	"VvvKV//+a0gbBzXN0NZr1Vj6kEzd6mRaTvahfsZTZ3umbLySfMCM0QuIB4wfv2L8YJd3APNsd702eNEV",
	"/bztqfhUtMDaBM/imwlQoe9xzCujf/Gt6Ica0stQPad9NwY5UO3dUsWuqdAHhtNT5MF61irbXjReGpHn",
	"aC5o0ATkbx8P5IaZj2G7VlnT30X+HRVUtnV75Mdyo2vFH45kc1CKKkJlBumiMxmYbr3suY+OuhgiSuj0",
	"aHpKvN5ZWgz6BV/TdPtdIsCeMuvC+TwL4lhZpSDUrGo4eF+upWSzDesfCP+HQ/2iKTj83rZFIQJm6yB3",
	"e7bLbtQfURV3IfGQqljKzsk/VurZrQdHi1pINxMKvoGstk6XTwYw9tj54i16uV/4nsNXDvIbjZc/Ns73",
	"2orH+dB14R2qj2DcfkVgjUq6lbeoZmTm87x5s2h74vrBooXPKFFi+RmsM3XmakoPdO2q2oHTLR85ZKFs",
	"hRkcNYzkkJ0MbYQnPXW5FNcERztkvo++BK3k+hja2pIBN2zpxQgcsG9ozS1b4XegdCBMhQ+EVnhuedF0",
	"/DMm5TQH3XzV6ivZ6LY3uv5k1tqaR2+vAe5HcC2n72YRuwnK9MbBYCjPIcZ8I/hdMGCJLtIp+b51X71L",
	"YwbJSsBPYQsZqUpe+tUG9nC/bDb2EU0kffzrjiZuOA9/jOSNFjrYVXQU3F4YM6kVzrSa+W5y0wZReNVu",
	"lOlqDYY179AxBWXtWPfebRdWhIJKsiyihMBKfQUl/IOFn5YzPNImKI0/ecRQ9Iq0zw6KQG2VsDPP6kuJ",
	"r15BbnxUd8CM2Ce5f4pSdeN7xUNmTD5y/KoF7ugtgVgWGz7qpIKybfeGGvfhFnrGcqHoBqQNzxE+vwqf",
	"S08r1+6nj17MwJ0FExyLPOijwuoZHJVUuSAH5mDOKjFfPfsOfOMUFij1lY87DcE2k2gtJdL+W5ekGe41",
	"0IhxcwDPDFzYTK88cePD5+SDrI0Pcq03jBid2s2csJ6DT0dj0w8Et/1Ss/1lutDLQYt+1r6ZGUiGVcP0",
	"TtfrWIbpem8H9TVV0tMi24esvgfhOdHB0lQhTpd9cf7hJXzj2ySsdoU2FNCW2mzmrm5QL7aH736KnT7K",
	"EM86og6vMaubrKhVSa1i+mRXoE23/4CtbZrB3fzm/+kSdLjK6JUgUxi0WsOVat/FHXSJmgWlJCdy938B",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
