// Code generated by service_registration.sh; DO NOT EDIT.

package services

import (
	servicemanager "github.com/psyb0t/gitrakz/internal/pkg/service-manager"
	httpserver "github.com/psyb0t/gitrakz/internal/pkg/services/http-server"
)

func Init() {
	sm := servicemanager.GetInstance()

	sm.Register(httpserver.ServiceName, func() (servicemanager.Service, error) {
		return httpserver.New()
	})

}
