// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/gitrakz/internal/pkg/db/models"
)

func newLLMCache(db *gorm.DB, opts ...gen.DOOption) lLMCache {
	_lLMCache := lLMCache{}

	_lLMCache.lLMCacheDo.UseDB(db, opts...)
	_lLMCache.lLMCacheDo.UseModel(&models.LLMCache{})

	tableName := _lLMCache.lLMCacheDo.TableName()
	_lLMCache.ALL = field.NewAsterisk(tableName)
	_lLMCache.Key = field.NewString(tableName, "key")
	_lLMCache.Step = field.NewString(tableName, "step")
	_lLMCache.ProcessingVersion = field.NewString(tableName, "processing_version")
	_lLMCache.InputHash = field.NewString(tableName, "input_hash")
	_lLMCache.Output = field.NewString(tableName, "output")
	_lLMCache.CreatedTS = field.NewInt64(tableName, "created_ts")

	_lLMCache.fillFieldMap()

	return _lLMCache
}

type lLMCache struct {
	lLMCacheDo

	ALL               field.Asterisk
	Key               field.String
	Step              field.String
	ProcessingVersion field.String
	InputHash         field.String
	Output            field.String
	CreatedTS         field.Int64

	fieldMap map[string]field.Expr
}

func (l lLMCache) Table(newTableName string) *lLMCache {
	l.lLMCacheDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lLMCache) As(alias string) *lLMCache {
	l.lLMCacheDo.DO = *(l.lLMCacheDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lLMCache) updateTableName(table string) *lLMCache {
	l.ALL = field.NewAsterisk(table)
	l.Key = field.NewString(table, "key")
	l.Step = field.NewString(table, "step")
	l.ProcessingVersion = field.NewString(table, "processing_version")
	l.InputHash = field.NewString(table, "input_hash")
	l.Output = field.NewString(table, "output")
	l.CreatedTS = field.NewInt64(table, "created_ts")

	l.fillFieldMap()

	return l
}

func (l *lLMCache) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lLMCache) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 6)
	l.fieldMap["key"] = l.Key
	l.fieldMap["step"] = l.Step
	l.fieldMap["processing_version"] = l.ProcessingVersion
	l.fieldMap["input_hash"] = l.InputHash
	l.fieldMap["output"] = l.Output
	l.fieldMap["created_ts"] = l.CreatedTS
}

func (l lLMCache) clone(db *gorm.DB) lLMCache {
	l.lLMCacheDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lLMCache) replaceDB(db *gorm.DB) lLMCache {
	l.lLMCacheDo.ReplaceDB(db)
	return l
}

type lLMCacheDo struct{ gen.DO }

type ILLMCacheDo interface {
	gen.SubQuery
	Debug() ILLMCacheDo
	WithContext(ctx context.Context) ILLMCacheDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILLMCacheDo
	WriteDB() ILLMCacheDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILLMCacheDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILLMCacheDo
	Not(conds ...gen.Condition) ILLMCacheDo
	Or(conds ...gen.Condition) ILLMCacheDo
	Select(conds ...field.Expr) ILLMCacheDo
	Where(conds ...gen.Condition) ILLMCacheDo
	Order(conds ...field.Expr) ILLMCacheDo
	Distinct(cols ...field.Expr) ILLMCacheDo
	Omit(cols ...field.Expr) ILLMCacheDo
	Join(table schema.Tabler, on ...field.Expr) ILLMCacheDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILLMCacheDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILLMCacheDo
	Group(cols ...field.Expr) ILLMCacheDo
	Having(conds ...gen.Condition) ILLMCacheDo
	Limit(limit int) ILLMCacheDo
	Offset(offset int) ILLMCacheDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILLMCacheDo
	Unscoped() ILLMCacheDo
	Create(values ...*models.LLMCache) error
	CreateInBatches(values []*models.LLMCache, batchSize int) error
	Save(values ...*models.LLMCache) error
	First() (*models.LLMCache, error)
	Take() (*models.LLMCache, error)
	Last() (*models.LLMCache, error)
	Find() ([]*models.LLMCache, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LLMCache, err error)
	FindInBatches(result *[]*models.LLMCache, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.LLMCache) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILLMCacheDo
	Assign(attrs ...field.AssignExpr) ILLMCacheDo
	Joins(fields ...field.RelationField) ILLMCacheDo
	Preload(fields ...field.RelationField) ILLMCacheDo
	FirstOrInit() (*models.LLMCache, error)
	FirstOrCreate() (*models.LLMCache, error)
	FindByPage(offset int, limit int) (result []*models.LLMCache, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILLMCacheDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l lLMCacheDo) Debug() ILLMCacheDo {
	return l.withDO(l.DO.Debug())
}

func (l lLMCacheDo) WithContext(ctx context.Context) ILLMCacheDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lLMCacheDo) ReadDB() ILLMCacheDo {
	return l.Clauses(dbresolver.Read)
}

func (l lLMCacheDo) WriteDB() ILLMCacheDo {
	return l.Clauses(dbresolver.Write)
}

func (l lLMCacheDo) Session(config *gorm.Session) ILLMCacheDo {
	return l.withDO(l.DO.Session(config))
}

func (l lLMCacheDo) Clauses(conds ...clause.Expression) ILLMCacheDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lLMCacheDo) Returning(value interface{}, columns ...string) ILLMCacheDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lLMCacheDo) Not(conds ...gen.Condition) ILLMCacheDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lLMCacheDo) Or(conds ...gen.Condition) ILLMCacheDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lLMCacheDo) Select(conds ...field.Expr) ILLMCacheDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lLMCacheDo) Where(conds ...gen.Condition) ILLMCacheDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lLMCacheDo) Order(conds ...field.Expr) ILLMCacheDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lLMCacheDo) Distinct(cols ...field.Expr) ILLMCacheDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lLMCacheDo) Omit(cols ...field.Expr) ILLMCacheDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lLMCacheDo) Join(table schema.Tabler, on ...field.Expr) ILLMCacheDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lLMCacheDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILLMCacheDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lLMCacheDo) RightJoin(table schema.Tabler, on ...field.Expr) ILLMCacheDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lLMCacheDo) Group(cols ...field.Expr) ILLMCacheDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lLMCacheDo) Having(conds ...gen.Condition) ILLMCacheDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lLMCacheDo) Limit(limit int) ILLMCacheDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lLMCacheDo) Offset(offset int) ILLMCacheDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lLMCacheDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILLMCacheDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lLMCacheDo) Unscoped() ILLMCacheDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lLMCacheDo) Create(values ...*models.LLMCache) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lLMCacheDo) CreateInBatches(values []*models.LLMCache, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lLMCacheDo) Save(values ...*models.LLMCache) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lLMCacheDo) First() (*models.LLMCache, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMCache), nil
	}
}

func (l lLMCacheDo) Take() (*models.LLMCache, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMCache), nil
	}
}

func (l lLMCacheDo) Last() (*models.LLMCache, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMCache), nil
	}
}

func (l lLMCacheDo) Find() ([]*models.LLMCache, error) {
	result, err := l.DO.Find()
	return result.([]*models.LLMCache), err
}

func (l lLMCacheDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LLMCache, err error) {
	buf := make([]*models.LLMCache, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lLMCacheDo) FindInBatches(result *[]*models.LLMCache, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lLMCacheDo) Attrs(attrs ...field.AssignExpr) ILLMCacheDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lLMCacheDo) Assign(attrs ...field.AssignExpr) ILLMCacheDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lLMCacheDo) Joins(fields ...field.RelationField) ILLMCacheDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lLMCacheDo) Preload(fields ...field.RelationField) ILLMCacheDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lLMCacheDo) FirstOrInit() (*models.LLMCache, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMCache), nil
	}
}

func (l lLMCacheDo) FirstOrCreate() (*models.LLMCache, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMCache), nil
	}
}

func (l lLMCacheDo) FindByPage(offset int, limit int) (result []*models.LLMCache, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lLMCacheDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lLMCacheDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lLMCacheDo) Delete(models ...*models.LLMCache) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lLMCacheDo) withDO(do gen.Dao) *lLMCacheDo {
	l.DO = *do.(*gen.DO)
	return l
}
