// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/gitrakz/internal/pkg/db/models"
)

func newLLMSettings(db *gorm.DB, opts ...gen.DOOption) lLMSettings {
	_lLMSettings := lLMSettings{}

	_lLMSettings.lLMSettingsDo.UseDB(db, opts...)
	_lLMSettings.lLMSettingsDo.UseModel(&models.LLMSettings{})

	tableName := _lLMSettings.lLMSettingsDo.TableName()
	_lLMSettings.ALL = field.NewAsterisk(tableName)
	_lLMSettings.ID = field.NewString(tableName, "id")
	_lLMSettings.Model = field.NewString(tableName, "model")
	_lLMSettings.ReasoningEffort = field.NewString(tableName, "reasoning_effort")
	_lLMSettings.Temperature = field.NewFloat64(tableName, "temperature")
	_lLMSettings.UpdatedTS = field.NewInt64(tableName, "updated_ts")

	_lLMSettings.fillFieldMap()

	return _lLMSettings
}

type lLMSettings struct {
	lLMSettingsDo

	ALL             field.Asterisk
	ID              field.String
	Model           field.String
	ReasoningEffort field.String
	Temperature     field.Float64
	UpdatedTS       field.Int64

	fieldMap map[string]field.Expr
}

func (l lLMSettings) Table(newTableName string) *lLMSettings {
	l.lLMSettingsDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lLMSettings) As(alias string) *lLMSettings {
	l.lLMSettingsDo.DO = *(l.lLMSettingsDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lLMSettings) updateTableName(table string) *lLMSettings {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewString(table, "id")
	l.Model = field.NewString(table, "model")
	l.ReasoningEffort = field.NewString(table, "reasoning_effort")
	l.Temperature = field.NewFloat64(table, "temperature")
	l.UpdatedTS = field.NewInt64(table, "updated_ts")

	l.fillFieldMap()

	return l
}

func (l *lLMSettings) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lLMSettings) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 5)
	l.fieldMap["id"] = l.ID
	l.fieldMap["model"] = l.Model
	l.fieldMap["reasoning_effort"] = l.ReasoningEffort
	l.fieldMap["temperature"] = l.Temperature
	l.fieldMap["updated_ts"] = l.UpdatedTS
}

func (l lLMSettings) clone(db *gorm.DB) lLMSettings {
	l.lLMSettingsDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lLMSettings) replaceDB(db *gorm.DB) lLMSettings {
	l.lLMSettingsDo.ReplaceDB(db)
	return l
}

type lLMSettingsDo struct{ gen.DO }

type ILLMSettingsDo interface {
	gen.SubQuery
	Debug() ILLMSettingsDo
	WithContext(ctx context.Context) ILLMSettingsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILLMSettingsDo
	WriteDB() ILLMSettingsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILLMSettingsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILLMSettingsDo
	Not(conds ...gen.Condition) ILLMSettingsDo
	Or(conds ...gen.Condition) ILLMSettingsDo
	Select(conds ...field.Expr) ILLMSettingsDo
	Where(conds ...gen.Condition) ILLMSettingsDo
	Order(conds ...field.Expr) ILLMSettingsDo
	Distinct(cols ...field.Expr) ILLMSettingsDo
	Omit(cols ...field.Expr) ILLMSettingsDo
	Join(table schema.Tabler, on ...field.Expr) ILLMSettingsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILLMSettingsDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILLMSettingsDo
	Group(cols ...field.Expr) ILLMSettingsDo
	Having(conds ...gen.Condition) ILLMSettingsDo
	Limit(limit int) ILLMSettingsDo
	Offset(offset int) ILLMSettingsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILLMSettingsDo
	Unscoped() ILLMSettingsDo
	Create(values ...*models.LLMSettings) error
	CreateInBatches(values []*models.LLMSettings, batchSize int) error
	Save(values ...*models.LLMSettings) error
	First() (*models.LLMSettings, error)
	Take() (*models.LLMSettings, error)
	Last() (*models.LLMSettings, error)
	Find() ([]*models.LLMSettings, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LLMSettings, err error)
	FindInBatches(result *[]*models.LLMSettings, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.LLMSettings) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILLMSettingsDo
	Assign(attrs ...field.AssignExpr) ILLMSettingsDo
	Joins(fields ...field.RelationField) ILLMSettingsDo
	Preload(fields ...field.RelationField) ILLMSettingsDo
	FirstOrInit() (*models.LLMSettings, error)
	FirstOrCreate() (*models.LLMSettings, error)
	FindByPage(offset int, limit int) (result []*models.LLMSettings, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILLMSettingsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l lLMSettingsDo) Debug() ILLMSettingsDo {
	return l.withDO(l.DO.Debug())
}

func (l lLMSettingsDo) WithContext(ctx context.Context) ILLMSettingsDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lLMSettingsDo) ReadDB() ILLMSettingsDo {
	return l.Clauses(dbresolver.Read)
}

func (l lLMSettingsDo) WriteDB() ILLMSettingsDo {
	return l.Clauses(dbresolver.Write)
}

func (l lLMSettingsDo) Session(config *gorm.Session) ILLMSettingsDo {
	return l.withDO(l.DO.Session(config))
}

func (l lLMSettingsDo) Clauses(conds ...clause.Expression) ILLMSettingsDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lLMSettingsDo) Returning(value interface{}, columns ...string) ILLMSettingsDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lLMSettingsDo) Not(conds ...gen.Condition) ILLMSettingsDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lLMSettingsDo) Or(conds ...gen.Condition) ILLMSettingsDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lLMSettingsDo) Select(conds ...field.Expr) ILLMSettingsDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lLMSettingsDo) Where(conds ...gen.Condition) ILLMSettingsDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lLMSettingsDo) Order(conds ...field.Expr) ILLMSettingsDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lLMSettingsDo) Distinct(cols ...field.Expr) ILLMSettingsDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lLMSettingsDo) Omit(cols ...field.Expr) ILLMSettingsDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lLMSettingsDo) Join(table schema.Tabler, on ...field.Expr) ILLMSettingsDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lLMSettingsDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILLMSettingsDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lLMSettingsDo) RightJoin(table schema.Tabler, on ...field.Expr) ILLMSettingsDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lLMSettingsDo) Group(cols ...field.Expr) ILLMSettingsDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lLMSettingsDo) Having(conds ...gen.Condition) ILLMSettingsDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lLMSettingsDo) Limit(limit int) ILLMSettingsDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lLMSettingsDo) Offset(offset int) ILLMSettingsDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lLMSettingsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILLMSettingsDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lLMSettingsDo) Unscoped() ILLMSettingsDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lLMSettingsDo) Create(values ...*models.LLMSettings) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lLMSettingsDo) CreateInBatches(values []*models.LLMSettings, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lLMSettingsDo) Save(values ...*models.LLMSettings) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lLMSettingsDo) First() (*models.LLMSettings, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMSettings), nil
	}
}

func (l lLMSettingsDo) Take() (*models.LLMSettings, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMSettings), nil
	}
}

func (l lLMSettingsDo) Last() (*models.LLMSettings, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMSettings), nil
	}
}

func (l lLMSettingsDo) Find() ([]*models.LLMSettings, error) {
	result, err := l.DO.Find()
	return result.([]*models.LLMSettings), err
}

func (l lLMSettingsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LLMSettings, err error) {
	buf := make([]*models.LLMSettings, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lLMSettingsDo) FindInBatches(result *[]*models.LLMSettings, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lLMSettingsDo) Attrs(attrs ...field.AssignExpr) ILLMSettingsDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lLMSettingsDo) Assign(attrs ...field.AssignExpr) ILLMSettingsDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lLMSettingsDo) Joins(fields ...field.RelationField) ILLMSettingsDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lLMSettingsDo) Preload(fields ...field.RelationField) ILLMSettingsDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lLMSettingsDo) FirstOrInit() (*models.LLMSettings, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMSettings), nil
	}
}

func (l lLMSettingsDo) FirstOrCreate() (*models.LLMSettings, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.LLMSettings), nil
	}
}

func (l lLMSettingsDo) FindByPage(offset int, limit int) (result []*models.LLMSettings, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lLMSettingsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lLMSettingsDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lLMSettingsDo) Delete(models ...*models.LLMSettings) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lLMSettingsDo) withDO(do gen.Dao) *lLMSettingsDo {
	l.DO = *do.(*gen.DO)
	return l
}
