// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	Document    *document
	Event       *event
	LLMCache    *lLMCache
	LLMSettings *lLMSettings
	SyncState   *syncState
	Template    *template
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Document = &Q.Document
	Event = &Q.Event
	LLMCache = &Q.LLMCache
	LLMSettings = &Q.LLMSettings
	SyncState = &Q.SyncState
	Template = &Q.Template
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Document:    newDocument(db, opts...),
		Event:       newEvent(db, opts...),
		LLMCache:    newLLMCache(db, opts...),
		LLMSettings: newLLMSettings(db, opts...),
		SyncState:   newSyncState(db, opts...),
		Template:    newTemplate(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Document    document
	Event       event
	LLMCache    lLMCache
	LLMSettings lLMSettings
	SyncState   syncState
	Template    template
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Document:    q.Document.clone(db),
		Event:       q.Event.clone(db),
		LLMCache:    q.LLMCache.clone(db),
		LLMSettings: q.LLMSettings.clone(db),
		SyncState:   q.SyncState.clone(db),
		Template:    q.Template.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Document:    q.Document.replaceDB(db),
		Event:       q.Event.replaceDB(db),
		LLMCache:    q.LLMCache.replaceDB(db),
		LLMSettings: q.LLMSettings.replaceDB(db),
		SyncState:   q.SyncState.replaceDB(db),
		Template:    q.Template.replaceDB(db),
	}
}

type queryCtx struct {
	Document    IDocumentDo
	Event       IEventDo
	LLMCache    ILLMCacheDo
	LLMSettings ILLMSettingsDo
	SyncState   ISyncStateDo
	Template    ITemplateDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Document:    q.Document.WithContext(ctx),
		Event:       q.Event.WithContext(ctx),
		LLMCache:    q.LLMCache.WithContext(ctx),
		LLMSettings: q.LLMSettings.WithContext(ctx),
		SyncState:   q.SyncState.WithContext(ctx),
		Template:    q.Template.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
