// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/gitrakz/internal/pkg/db/models"
)

func newSyncState(db *gorm.DB, opts ...gen.DOOption) syncState {
	_syncState := syncState{}

	_syncState.syncStateDo.UseDB(db, opts...)
	_syncState.syncStateDo.UseModel(&models.SyncState{})

	tableName := _syncState.syncStateDo.TableName()
	_syncState.ALL = field.NewAsterisk(tableName)
	_syncState.Owner = field.NewString(tableName, "owner")
	_syncState.Repo = field.NewString(tableName, "repo")
	_syncState.LastSyncedTS = field.NewInt64(tableName, "last_synced_ts")

	_syncState.fillFieldMap()

	return _syncState
}

type syncState struct {
	syncStateDo

	ALL          field.Asterisk
	Owner        field.String
	Repo         field.String
	LastSyncedTS field.Int64

	fieldMap map[string]field.Expr
}

func (s syncState) Table(newTableName string) *syncState {
	s.syncStateDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s syncState) As(alias string) *syncState {
	s.syncStateDo.DO = *(s.syncStateDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *syncState) updateTableName(table string) *syncState {
	s.ALL = field.NewAsterisk(table)
	s.Owner = field.NewString(table, "owner")
	s.Repo = field.NewString(table, "repo")
	s.LastSyncedTS = field.NewInt64(table, "last_synced_ts")

	s.fillFieldMap()

	return s
}

func (s *syncState) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *syncState) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 3)
	s.fieldMap["owner"] = s.Owner
	s.fieldMap["repo"] = s.Repo
	s.fieldMap["last_synced_ts"] = s.LastSyncedTS
}

func (s syncState) clone(db *gorm.DB) syncState {
	s.syncStateDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s syncState) replaceDB(db *gorm.DB) syncState {
	s.syncStateDo.ReplaceDB(db)
	return s
}

type syncStateDo struct{ gen.DO }

type ISyncStateDo interface {
	gen.SubQuery
	Debug() ISyncStateDo
	WithContext(ctx context.Context) ISyncStateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISyncStateDo
	WriteDB() ISyncStateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISyncStateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISyncStateDo
	Not(conds ...gen.Condition) ISyncStateDo
	Or(conds ...gen.Condition) ISyncStateDo
	Select(conds ...field.Expr) ISyncStateDo
	Where(conds ...gen.Condition) ISyncStateDo
	Order(conds ...field.Expr) ISyncStateDo
	Distinct(cols ...field.Expr) ISyncStateDo
	Omit(cols ...field.Expr) ISyncStateDo
	Join(table schema.Tabler, on ...field.Expr) ISyncStateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISyncStateDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISyncStateDo
	Group(cols ...field.Expr) ISyncStateDo
	Having(conds ...gen.Condition) ISyncStateDo
	Limit(limit int) ISyncStateDo
	Offset(offset int) ISyncStateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISyncStateDo
	Unscoped() ISyncStateDo
	Create(values ...*models.SyncState) error
	CreateInBatches(values []*models.SyncState, batchSize int) error
	Save(values ...*models.SyncState) error
	First() (*models.SyncState, error)
	Take() (*models.SyncState, error)
	Last() (*models.SyncState, error)
	Find() ([]*models.SyncState, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SyncState, err error)
	FindInBatches(result *[]*models.SyncState, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SyncState) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISyncStateDo
	Assign(attrs ...field.AssignExpr) ISyncStateDo
	Joins(fields ...field.RelationField) ISyncStateDo
	Preload(fields ...field.RelationField) ISyncStateDo
	FirstOrInit() (*models.SyncState, error)
	FirstOrCreate() (*models.SyncState, error)
	FindByPage(offset int, limit int) (result []*models.SyncState, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISyncStateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s syncStateDo) Debug() ISyncStateDo {
	return s.withDO(s.DO.Debug())
}

func (s syncStateDo) WithContext(ctx context.Context) ISyncStateDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s syncStateDo) ReadDB() ISyncStateDo {
	return s.Clauses(dbresolver.Read)
}

func (s syncStateDo) WriteDB() ISyncStateDo {
	return s.Clauses(dbresolver.Write)
}

func (s syncStateDo) Session(config *gorm.Session) ISyncStateDo {
	return s.withDO(s.DO.Session(config))
}

func (s syncStateDo) Clauses(conds ...clause.Expression) ISyncStateDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s syncStateDo) Returning(value interface{}, columns ...string) ISyncStateDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s syncStateDo) Not(conds ...gen.Condition) ISyncStateDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s syncStateDo) Or(conds ...gen.Condition) ISyncStateDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s syncStateDo) Select(conds ...field.Expr) ISyncStateDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s syncStateDo) Where(conds ...gen.Condition) ISyncStateDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s syncStateDo) Order(conds ...field.Expr) ISyncStateDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s syncStateDo) Distinct(cols ...field.Expr) ISyncStateDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s syncStateDo) Omit(cols ...field.Expr) ISyncStateDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s syncStateDo) Join(table schema.Tabler, on ...field.Expr) ISyncStateDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s syncStateDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISyncStateDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s syncStateDo) RightJoin(table schema.Tabler, on ...field.Expr) ISyncStateDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s syncStateDo) Group(cols ...field.Expr) ISyncStateDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s syncStateDo) Having(conds ...gen.Condition) ISyncStateDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s syncStateDo) Limit(limit int) ISyncStateDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s syncStateDo) Offset(offset int) ISyncStateDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s syncStateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISyncStateDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s syncStateDo) Unscoped() ISyncStateDo {
	return s.withDO(s.DO.Unscoped())
}

func (s syncStateDo) Create(values ...*models.SyncState) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s syncStateDo) CreateInBatches(values []*models.SyncState, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s syncStateDo) Save(values ...*models.SyncState) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s syncStateDo) First() (*models.SyncState, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncState), nil
	}
}

func (s syncStateDo) Take() (*models.SyncState, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncState), nil
	}
}

func (s syncStateDo) Last() (*models.SyncState, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncState), nil
	}
}

func (s syncStateDo) Find() ([]*models.SyncState, error) {
	result, err := s.DO.Find()
	return result.([]*models.SyncState), err
}

func (s syncStateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SyncState, err error) {
	buf := make([]*models.SyncState, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s syncStateDo) FindInBatches(result *[]*models.SyncState, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s syncStateDo) Attrs(attrs ...field.AssignExpr) ISyncStateDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s syncStateDo) Assign(attrs ...field.AssignExpr) ISyncStateDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s syncStateDo) Joins(fields ...field.RelationField) ISyncStateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s syncStateDo) Preload(fields ...field.RelationField) ISyncStateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s syncStateDo) FirstOrInit() (*models.SyncState, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncState), nil
	}
}

func (s syncStateDo) FirstOrCreate() (*models.SyncState, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncState), nil
	}
}

func (s syncStateDo) FindByPage(offset int, limit int) (result []*models.SyncState, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s syncStateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s syncStateDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s syncStateDo) Delete(models ...*models.SyncState) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *syncStateDo) withDO(do gen.Dao) *syncStateDo {
	s.DO = *do.(*gen.DO)
	return s
}
